function snr = Propogation(Htar, RCS, info, t_pulse, patternLoss, scanLoss)
    max_pulse = max(info.t_pulses);
    snr = info.snr.*...
        (t_pulse./max_pulse).*...
        (info.Hmax./Htar).^4.*...
        scanLoss.*patternLoss.*...
        RCS./info.averRSC;
end

